[book]
src = "src"

[output.html]
theme = "theme"
default-theme = "solarized-light"
#preferred-dark-theme = "solarized-dark"
additional-css = [
  "solarized-light-hljs.css",
  "solarized-dark-hljs.css"
]
additional-js = [
  "theme-solarized_dark.js",
  "theme-solarized_light.js",
]

[output.html.playpen]
editable = true
line-numbers = true

[output.html.search]
enable = false